name = "bandofbakers-v2"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "bandofbakers-db"
database_id = "placeholder-id"

[[kv_namespaces]]
binding = "KV"
id = "placeholder-id"

[[r2_buckets]]
binding = "R2"
bucket_name = "bandofbakers-assets"
